import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { expect, it } from 'vitest';
import { completeFlatOVG } from '../src/tala/ovg-finalize.js';
import type { OVGFlatEdge, OVGFlatNode } from '../src/tala/ovg-build.js';

const read = (file: string) => JSON.parse(readFileSync(new URL(
  `../tools/upstream-fixtures/${file}`, import.meta.url), 'utf8'));

it('matches upstream mixed hierarchy OVG vertices and edges', () => {
  const input = read('compound-stress-cases.json').find(
    (item: { name: string }) => item.name === 'grouped-tree-TB') as {
    nodes: OVGFlatNode[]; edges: OVGFlatEdge[] };
  const oracle = read('compound-stress-expected.json').find(
    (item: { name: string }) => item.name === 'grouped-tree-TB') as {
    nodes: OVGFlatNode[] };
  const nodes = oracle.nodes.map((node) => ({
    ...input.nodes.find((item) => item.id === node.id), ...node,
  }));
  const hierarchy = { levels: new Map([
    ['Root', 0], ['Left', 1], ['Right', 1], ['Leaf1', 2], ['Leaf2', 2],
  ]), direction: 'TB' as const };
  const graph = completeFlatOVG(nodes, input.edges, hierarchy);
  const vertices = graph.vertices.map((point) => [point.x, point.y]).sort(pointOrder);
  const segments = graph.edgeObjects.map((edge) => {
    const a = [edge.from.x, edge.from.y], b = [edge.to.x, edge.to.y];
    return pointOrder(a, b) <= 0 ? [...a, ...b] : [...b, ...a];
  }).sort(pointOrder);
  // Generated by the pinned Go routing/ovg.go pipeline on these exact boxes.
  const digest = createHash('sha256').update(JSON.stringify({ vertices, segments }))
    .digest('hex');
  expect(graph.vertices).toHaveLength(811);
  expect(graph.edgeObjects).toHaveLength(1463);
  expect(digest).toBe('fea76386741f9bf885df51dd6753acdb779c6891e30eef215e0699e5ec115d9c');
});

function pointOrder(a: number[], b: number[]): number {
  for (let index = 0; index < a.length; index++) {
    if (a[index] !== b[index]) return a[index]! - b[index]!;
  }
  return 0;
}
